---

- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks:
      - tasks/dev-tools.yml
      - tasks/graphics.yml
      - tasks/utils.yml