---

- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/dev-tools.yml
    - include_tasks: tasks/graphics.yml
    - include_tasks: tasks/utils.yml
    - include_tasks: tasks/pgadmin.yml
    - include_tasks: tasks/dropbox.yml
    - include_tasks: tasks/snaps.yml
