---
- name: Install dev packages
  apt: name={{item}}
  with_items:
    - age
    - analog
    - apache2
    - apache2-utils
    - autoconf
    - automake
    - build-essential
    - bzip2
    - cpp
    - csvkit
    - default-jdk
    - direnv
    - docker-compose
    - g++
    - gcc
    - gdal-bin
    - gdal-data
    - gdal-plugins
    - gh
    - java-common
    - jq
    - make
    - postgresql
    - postgis
    - postgresql-client
    - qgis
    - tidy
    - time
    - tmux
    - vim
    - virtualbox
    - virtualbox-guest-utils
    - virtualbox-guest-additions-iso
    - xgrep
    - xsltproc

- name: install asdf
  become_user: ian
  ansible.builtin.shell: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
    creates: ~/.asdf

