---
- name: Install dev packages
  apt: name={{item}}
  with_items:
    - age
    - analog
    - apache2
    - apache2-utils
    - autoconf
    - automake
    - build-essential
    - bzip2
    - cpp
    - csvkit
    - default-jdk
    - direnv
    - docker-compose
    - fop
    - g++
    - gcc
    - gdal-bin
    - gdal-data
    - gdal-plugins
    - gh
    - java-common
    - jq
    - libbz2-dev
    - libffi-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libwxgtk-webview3.2-dev
    - libxml2-utils
    - liblzma-dev
    - make
    - net-tools
    - postgresql
    - postgis
    - postgresql-client
    - qgis
    - tidy
    - time
    - tk-dev
    - tmux
    - unixodbc
    - unixodbc-dev
    - vim
    - virtualbox
    - virtualbox-guest-utils
    - virtualbox-guest-additions-iso
    - xgrep
    - xsltproc

- name: gather asdf install status
  become_user: ian
  stat: 
    path: /home/ian/.asdf
  register: asdf_status
  
- name: install asdf
  become_user: ian
  ansible.builtin.shell: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
  when: not asdf_status.stat.exists
  
- name: install asdf plugin node
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  when: not asdf_status.stat.exists
  
- name: install asdf plugin erlang
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
  when: not asdf_status.stat.exists
  
- name: install asdf plugin elixir
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
  when: not asdf_status.stat.exists
  
- name: install asdf plugin python
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add python https://github.com/danhper/asdf-python.git
  when: not asdf_status.stat.exists
  
- name: install asdf plugin ruby
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  when: not asdf_status.stat.exists
  
- name: install asdf plugin golang
  become_user: ian
  ansible.builtin.shell: /home/ian/.asdf/bin/asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
  when: not asdf_status.stat.exists

