---
- name: Install dev packages
  apt: name={{item}}
  with_items:
    - age
    - analog
    - apache2
    - apache2-utils
    - autoconf
    - automake
    - build-essential
    - bzip2
    - cpp
    - csvkit
    - default-jdk
    - direnv
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - g++
    - gcc
    - gdal-bin
    - gdal-data
    - gdal-plugins
    - gh
    - java-common
    - jq
    - make
    - pgadmin4
    - postgresql
    - postgresql-14
    - postgis
    - postgresql-client
    - qgis
    - tidy
    - time
    - tmux
    - vim
    - virtualbox
    - virtualbox-guest-utils
    - virtualbox-guest-additions-iso
    - xgrep
    - xsltproc
