---

- name: dropbox | Install Dropbox key
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: dropbox | Install Dropbox repository
  apt_repository:
    repo: deb [arch=i386,amd64] https://linux.dropbox.com/ubuntu lunar main
    state: present
    filename: dropbox

- name: dropbox | install supporting packages
  apt:
    name: python3-gpg
    state: present

- name: dropbox | Install Dropbox
  apt:
    name: dropbox
    state: present
