---

- name: install snap packages
  community.general.snap: name={{item}}
  with_items:
    - bitwarden
    - btop
    - chromium
    - code
    - discord
    - exercism
    - kompare
    - skype
    - slack
    - spotify

- name: install vscode package with confinement=classic
  community.general.snap:
    name: code
    classic: true
