---

- name: install snap packages
  community.general.snap: name={{item}}
  with_items:
    - bitwarden
    - btop
    - discord
    - exercism
    - kompare
    - skype
    - slack
    - spotify

- name: install snap packages with confinement=classic
  community.general.snap: name={{item}}
  with_items:
    - code
  classic: true
