---

- name: install snap packages
  community.general.snap: name={{item}}
  with_items:
    - bitwarden
    - btop
    - code
    - discord
    - exercism
    - kompare
    - skype
    - slack
    - spotify
