---

- name: Get zoom gpg key
  ansible.builtin.apt_key:
    url: https://zoom.us/linux/download/pubkey?version=5-12-6
    state: present

- name: Install zoom from .deb
  apt:
    deb: https://zoom.us/client/5.16.6.382/zoom_amd64.deb
